[[customizing]]
== 自定义 ==

[[customizing-notifiers]]
=== 自定义通知器 ===

你可以实现 `Notifier` 接口，以Spring Beans的形式添加自己的通知程序，当然最好是继承 `AbstractEventNotifier` 或 `AbstractStatusChangeNotifier` 的方式。

[source,java,indent=0]
----
include::{samples-dir}/spring-boot-admin-sample-servlet/src/main/java/de/codecentric/boot/admin/CustomNotifier.java[tags=customization-notifiers]
----

[[customizing-headers]]
=== 自定义HTTP请求头 ===

为了监控应用而发送的actuator接口，如果你需要在其中添加自定义HTTP请求头的话，可以使用 `HttpHeadersProvider` 来轻松的实现:

[source,java,indent=0]
----
include::{samples-dir}/spring-boot-admin-sample-servlet/src/main/java/de/codecentric/boot/admin/SpringBootAdminServletApplication.java[tags=customization-http-headers-providers]
----

[[customizing-instance-filter]]
=== 对请求和响应进行拦截 ===

为了监控应用而发送的actuator接口，如果你需要拦截并修改其请求以及响应的话，可以通过实现 `InstanceExchangeFilterFunction` 来完成。 这对审核或者是添加额外的安全检查很有作用。

[source,java,indent=0]
----
include::{samples-dir}/spring-boot-admin-sample-servlet/src/main/java/de/codecentric/boot/admin/SpringBootAdminServletApplication.java[tags=customization-instance-exchange-filter-function]
----

[[customizing-external-views]]
=== 链接/嵌入外部页面 ===

你可以非常简单的通过配置添加一个外部页面的链接甚至是直接将他们嵌入进来 (添加 `iframe=true` 参数)。

[source,yaml,indent=0]
----
include::{samples-dir}/spring-boot-admin-sample-servlet/src/main/resources/application.yml[tags=customization-external-views]
----

[[customizing-custom-views]]
=== 自定义页面 ===

您也可以向前端添加自定义页面。页面必须是一个 https://vuejs.org/[Vue.js] 组件。

js文件还有css样式表必须放在classpath下的 `/META-INF/spring-boot-admin-server-ui/extensions/{name}/` 路径，这样服务端才能拿到它们。
{github-src}/spring-boot-admin-samples/spring-boot-admin-sample-custom-ui/[spring-boot-admin-sample-custom-ui] 模块中包含了一个示例，该示例展示了如何配置maven来成功的构建一个模块。

要想自定义拓展将自己注册，可以调用 `SBA.use()` 然后还需要暴露 `install()` 函数，这在配置路由参数的时候会被ui调用。
`install()` 函数在注册页面和/或是回调时接收以下参数:

* {github-src}/spring-boot-admin-server-ui/src/main/frontend/viewRegistry.js[viewRegistry] 的对象引用

* {github-src}/spring-boot-admin-server-ui/src/main/frontend/store.js[applicationStore] 的对象引用

* the global Vue[Vue] 的对象引用

* {github-src}/spring-boot-admin-server-ui/src/main/frontend/utils/axios.js[axios] 的对象引用

如果前端添加了顶级路由，那么后端也必须知道。 可以在 `/META-INF/spring-boot-admin-server-ui/extensions/{name}/routes.txt` 文件配置所有的顶级路由，每个路由占一行。

[[customizing-custom-views-top-level]]
==== 添加顶级页面 ====

下面是一个简单的顶级页面示例，其中列表出所有已注册的应用:
[source,html]

----
include::{samples-dir}/spring-boot-admin-sample-custom-ui/src/custom.vue[lines=17..-1]
----

<1> 如果你在组件中定义了 `applications` 属性，组件会将所有已注册的应用注入进来。

TIP: 应用中还提供了一些很有用的方法和可用的实例对象。可以参考 {github-src}/spring-boot-admin-server-ui/src/main/frontend/services/application.js[application.js] 以及 {github-src}/spring-boot-admin-server-ui/src/main/frontend/services/instance.js[instance.js]。

这里展示了如何注册顶级试图。
[source,javascript]

----
include::{samples-dir}/spring-boot-admin-sample-custom-ui/src/index.js[tags=customization-ui-toplevel]
----

<1> 试图以及路由名称
<2> 试图的访问路径
<3> 引用的自定义组件，将会在路由上渲染
<4> 在顶部导航栏显示自定义试图的label
<5> 对试图进行排序。顶部导航栏中的试图是按照升序进行排序的。

添加了路由的 `routes.txt` 文件:
[source,text]

----
include::{samples-dir}/spring-boot-admin-sample-custom-ui/src/routes.txt[]
----

[[customizing-custom-views-instance]]
==== 查看自定义接口 ====

下面是调用自定义接口的试图:
[source,html]

----
include::{samples-dir}/spring-boot-admin-sample-custom-ui/src/custom-endpoint.vue[lines=17..-1]
----

<1> 如果你在组件中定义了 `instance` 属性，组件会将需要渲染的对象注入进来。

<2> 所有的实例中都提前配置好了 https://github.com/axios/axios[axios] 供您访问，您只需要输入正确的路径和请求头就好了。

注册实例的工作方式与顶级试图差不多，但有一些额外的附加属性:
[source,javascript]

----
include::{samples-dir}/spring-boot-admin-sample-custom-ui/src/index.js[tags=customization-ui-endpoint]
----

<1> 这里的parent必须是 'instances' ，这样才能为单例提供新的自定义试图。
<2> 可以对试图进行分组。
<3> 如果添加了 `isEnabled` 选项，则可以动态判断是否为特定实例显示试图。
<4> 注册自定义i18n翻译

NOTE: 你可以以同分组、同名试图的方式对默认试图进行覆盖。

=== 自定义顶部Logo和标题 ===

你可以使用下列属性对标题中的信息（例如显示登录信息或者是公司名称）进行自定义:

- **spring.boot.admin.ui.brand**: 这段HTML会渲染到导航标题中，默认是 `<img src="assets/img/icon-spring-boot-admin.svg"><span>Spring Boot Admin</span>`。
默认情况下这里会显示SBA的logo，后面加上名称。
你可以在 `/META-INF/spring-boot-admin-server-ui/` 这个路径（SBA默认会从这个路径下注册 `ResourceHandler` ）下添加图片，或者用其它方式确保正确的提供图片（比如手动注册 `ResourceHandler` ）。

- **spring.boot.admin.ui.title**: 使用这个选项可以自定义浏览器窗口标题。

=== 自定义登录Logo ===

你可以自定义登录页面的图片。

1. 将图片放在http可以访问到的资源目录下（例如 `/META-INF/spring-boot-admin-server-ui/assets/img/`）。
2. 使用下面的属性来配置要使用的图标:
- **spring.boot.admin.ui.login-icon**: 用作登录页面上的图标(例 `assets/img/custom-login-icon.svg`)。

=== 自定义Favicon ===

可以使用自定义的favicon，它也会用在桌面通知上。
当有一个或多个应用关闭时，Spring Boot Admin会使用不同的图标。

1. 将favicon图标（`.png` 格式，最低192x192像素）放在http可以访问到的资源目录下（例如 `/META-INF/spring-boot-admin-server-ui/assets/img/`）。

2. 下面的属性可以配置要使用的图标:
- `spring.boot.admin.ui.favicon`: 配置默认图标(例 `assets/img/custom-favicon.png`) 。
- `spring.boot.admin.ui.favicon-danger`: 在一个或多个服务关闭时使用这个图标 (例 `assets/img/custom-favicon-danger.png`)。

=== 自定义可用语言 ===

要想筛选所有支持的语言，可以使用下面的选项:

- **spring.boot.admin.ui.available-languages**: 配置现有语言的过滤器 (例如 `en,de` out of existing `de,en,fr,ko,pt-BR,ru,zh`)。

=== 显示/隐藏页面 ===

要想在导航栏中隐藏试图，可以很简单的实现：

[source,yaml,indent=0]
----
include::{samples-dir}/spring-boot-admin-sample-servlet/src/main/resources/application.yml[tags=customization-view-settings]
----
