[[getting-started]]
== 入门 ==

[[set-up-admin-server]]
=== 配置SBA服务端应用程序 ===

第一步，你需要配置你的服务端程序。
为此，只需要配置一个基础的boot项目（使用 http://start.spring.io 生成脚手架）。
由于Spring Boot Admin Server同时支持servlet和webflux，所以你需要在其中进行选择，并添加对应的Spring Boot Starter。
在本例中，我们使用servlet作为web starter。

. 将Spring Boot Admin Server的starter添加到你的依赖中:
+
[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>spring-boot-admin-starter-server</artifactId>
    <version>{project-version}</version>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
</dependency>
----

[TIP]
====
如果你使用的是Spring Boot Admin Server的snapshot版本，那么可能还需要添加spring的sonatype snapshot仓库:

[source,xml]
.pom.xml
----
<repositories>
    <repository>
        <id>spring-milestone</id>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <url>http://repo.spring.io/milestone</url>
    </repository>
    <repository>
        <id>spring-snapshot</id>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
        <url>http://repo.spring.io/snapshot</url>
    </repository>
    <repository>
        <id>sonatype-nexus-snapshots</id>
        <name>Sonatype Nexus Snapshots</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
        <releases>
            <enabled>false</enabled>
        </releases>
    </repository>
</repositories>
----
====

. 在main class上添加`@EnableAdminServer`注解，启用SBA服务器端配置:
+
[source,java]
----
@Configuration
@EnableAutoConfiguration
@EnableAdminServer
public class SpringBootAdminApplication {
    public static void main(String[] args) {
        SpringApplication.run(SpringBootAdminApplication.class, args);
    }
}
----

NOTE: 如果你想通过部署war包，以servlet容器的方式来设置SBA，那么请查看 {github-src}/spring-boot-admin-samples/spring-boot-admin-sample-war/[spring-boot-admin-sample-war]。

同时也看看 {github-src}/spring-boot-admin-samples/spring-boot-admin-sample-servlet/[spring-boot-admin-sample-servlet]，
其中添加了安全保护。

[[register-client-applications]]
=== 注册客户端应用程序 ===

要想在SBA服务端注册你的应用，你需要引入SBA客户端，或者是使用
https://spring.io/projects/spring-cloud[Spring Cloud服务发现] (例如 Eureka、Consul等等)。
这里有一个
<<spring-cloud-discovery-static-config,在SBA服务端使用静态配置的简单选项>>。

[[register-clients-via-spring-boot-admin]]
==== SBA客户端服务 ====

所有要注册的应用都需要添加Spring Boot Admin客户端依赖。
如果要想对默认接口进行安全保护，还需要添加 `spring-boot-starter-security` 依赖。

. 添加spring-boot-admin-starter-client依赖:
+
[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>spring-boot-admin-starter-client</artifactId>
    <version>{project-version}</version>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
</dependency>
----

. 配置Spring Boot Admin服务端的URL来开启SBA客户端:
+
[source]
.application.properties
----
spring.boot.admin.client.url=http://localhost:8080  #<1>
management.endpoints.web.exposure.include=*  #<2>
management.info.env.enabled=true #<3>
----
<1> 将要注册到的Spring Boot Admin 服务端URL地址。
<2> 与Spring Boot 2一样，大部分默认接口都没有通过http暴露出来，这里我们将它们全部暴露。在生产环境，您应该酌情选择您要公开的接口。
<3> 在Spring Boot 2.6版本之后，env信息默认是关闭的。所以我们必须启用它们。

. 让所有的actuator接口都可以访问:
+
[source,java]
----
@Configuration
public static class SecurityPermitAllConfig extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests().anyRequest().permitAll()  //<1>
            .and().csrf().disable();
    }
}
----
<1> 为了演示的简单，我们禁用了安全功能。请查看 <<securing-spring-boot-admin,安全处理章节>> 来学习如何保护您的接口。

[[discover-clients-via-spring-cloud-discovery]]
==== Spring Cloud 服务发现 ====

If you already use Spring Cloud Discovery for your applications you don't need the SBA Client. Just add a DiscoveryClient to Spring Boot Admin Server, the rest is done by our AutoConfiguration.

The following steps uses Eureka, but other Spring Cloud Discovery implementations are supported as well. There are examples using {github-src}/spring-boot-admin-samples/spring-boot-admin-sample-consul/[Consul] and https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-zookeeper/[Zookeeper].

Also, have a look at the http://projects.spring.io/spring-cloud/spring-cloud.html[Spring Cloud documentation].

. Add spring-cloud-starter-eureka to your dependencies:
+
[source,xml]
.pom.xml
----
include::{samples-dir}/spring-boot-admin-sample-eureka/pom.xml[tags=dependency-eureka,indent=0]
----

. Enable discovery by adding `@EnableDiscoveryClient` to your configuration:
+
[source,java]
----
@Configuration
@EnableAutoConfiguration
@EnableDiscoveryClient
@EnableScheduling
@EnableAdminServer
public class SpringBootAdminApplication {
    public static void main(String[] args) {
        SpringApplication.run(SpringBootAdminApplication.class, args);
    }

    @Configuration
    public static class SecurityPermitAllConfig extends WebSecurityConfigurerAdapter {
        @Override
        protected void configure(HttpSecurity http) throws Exception {
            http.authorizeRequests().anyRequest().permitAll()  //<1>
                .and().csrf().disable();
        }
    }
}
----
<1> For the sake of brevity we're disabling the security for now. Have a look at the <<securing-spring-boot-admin,security section>> on how to deal with secured endpoints.


. Tell the Eureka client where to find the service registry:
+
[source,yml]
.application.yml
----
include::{samples-dir}/spring-boot-admin-sample-eureka/src/main/resources/application.yml[tags=configuration-eureka]
----
<1> Configuration section for the Eureka client
<2> As with Spring Boot 2 most of the endpoints aren't exposed via http by default, we expose all of them. For production you should carefully choose which endpoints to expose.

See also {github-src}/spring-boot-admin-samples/spring-boot-admin-sample-eureka/[spring-boot-admin-sample-eureka].

TIP: You can include the Spring Boot Admin Server to your Eureka server. Setup everything as described above and set `spring.boot.admin.context-path` to something different than `"/"` so that the Spring Boot Admin Server UI won't clash with Eureka's one.

[[register-python-applications]]
==== 使用Pyctuator注册Python应用程序 ====

You can easily integrate Spring Boot Admin with https://flask.palletsprojects.com[Flask] or https://fastapi.tiangolo.com/[FastAPI] Python applications using the https://github.com/SolarEdgeTech/pyctuator[Pyctuator] project.


The following steps uses Flask, but other web frameworks are supported as well. See Pyctuator's documentation for an updated list of supported frameworks and features.

. Install the pyctuator package:
+
[source,bash]
----
pip install pyctuator
----

. Enable pyctuator by pointing it to your Flask app and letting it know where Spring Boot Admin is running:
+
[source,python]
----
import os
from flask import Flask
from pyctuator.pyctuator import Pyctuator

app_name = "Flask App with Pyctuator"
app = Flask(app_name)


@app.route("/")
def hello():
    return "Hello World!"


Pyctuator(
    app,
    app_name,
    app_url="http://example-app.com",
    pyctuator_endpoint_url="http://example-app.com/pyctuator",
    registration_url=os.getenv("SPRING_BOOT_ADMIN_URL")
)

app.run()
----

For further details and examples, see Pyctuator's https://github.com/SolarEdgeTech/pyctuator/blob/master/README.md[documentation] and https://github.com/SolarEdgeTech/pyctuator/tree/master/examples[examples].
